### ISSUE TITLE
Preparation of the programming environment

### ISSUE THREAD

**Issue by jonabasque** [influyentes/influyentes#7]
- [ ] Create the structure with:
  - [x] Rails 5
  - [ ] Angular 1.5
  - [x] PostgreSQL 9.4
  - [ ] Other gems.
- [x] Set the testing environment with:
  - [x] Rspec
  - [x] Circle CI
  - [x] Codeclimate
  - [x] Hound
  - [x] Rubocop

**Comment by WaKeMaTTa** [comment]
duplicated https://github.com/influyentes/influyentes/issues/5
